import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    fastDelivery: false,
    price: "4000",
    originalPrice: "6000",
    categoryName: "Whey Protein",
    brand: "MuscleBlaze",
    stockQuantity: 3,
    img: "https://rukminim2.flixcart.com/image/612/612/k226oi80/protein-supplement/z/v/x/whey-performance-nut5706-02-muscleblaze-original-imafhhrrvxxrnk33.jpeg?q=70",
    rating: 1.9,
    newArrival: true,
  },
  {
    _id: uuid(),
    fastDelivery: true,
    price: "5000",
    originalPrice: "8000",
    categoryName: "Whey Protein",
    brand: "MyProtein",
    stockQuantity: 5,
    img: "https://m.media-amazon.com/images/I/31YRR7gYk8L._AC_UL480_FMwebp_QL65_.jpg",
    rating: 4.7,
    newArrival: false,
  },
  {
    _id: uuid(),
    fastDelivery: false,
    price: "3000",
    originalPrice: "6000",
    categoryName: "Mass Gainer",
    brand: "Muscle Blaze",
    stockQuantity: 0,
    img: " https://rukminim2.flixcart.com/image/612/612/k4a7c7k0/protein-supplement/v/m/v/gold-gainer-xxl-nut6234-03-muscleblaze-original-imafn7dgft9y9qee.jpeg?q=70",
    rating: 3.8,
    newArrival: false,
  },
  {
    _id: uuid(),
    fastDelivery: false,
    price: "9800",
    originalPrice: "13000",
    categoryName: "Whey Protein",
    brand: "Dynamatize",
    stockQuantity: 5,
    img: "https://rukminim2.flixcart.com/image/612/612/l0sgyvk0/protein-supplement/b/g/x/whey-protein-iso100-hydrolized-protein-powder-63-ser-2-3kg-5lbs-original-imagcg3ah94anqhn.jpeg?q=70",
    rating: 4.9,
    newArrival: true,
  },
  {
    _id: uuid(),
    fastDelivery: false,
    price: "1100",
    originalPrice: "2000",
    categoryName: "Mass Gainer",
    brand: "MyProtein",
    stockQuantity: 5,
    img: "https://m.media-amazon.com/images/I/31NIEZqxwBS._AC_UL480_FMwebp_QL65_.jpg",
    rating: 3.8,
    newArrival: false,
  },

  {
    _id: uuid(),
    fastDelivery: false,
    price: "8000",
    originalPrice: "10000",
    categoryName: "Mass Gainer",
    brand: "ON Nutrition",
    stockQuantity: 0,
    img: "https://rukminim2.flixcart.com/image/612/612/kd69z0w0/protein-supplement/f/f/z/serious-mass-748927062960-optimum-nutrition-original-imafu4ywnsnmhhbr.jpeg?q=70",
    rating: 2.8,
    newArrival: false,
  },
  {
    _id: uuid(),
    fastDelivery: true,
    price: "1200",
    originalPrice: "2000",
    categoryName: "Mass Gainer",
    brand: "Dynamatize",
    stockQuantity: 5,
    img: "https://m.media-amazon.com/images/I/818Hq49X08L._AC_UL480_FMwebp_QL65_.jpg",
    rating: 2.9,
    newArrival: true,
  },
  {
    _id: uuid(),
    fastDelivery: false,
    price: "1500",
    originalPrice: "2500",
    categoryName: "PreWorkout",
    brand: "Cellucor C4",
    stockQuantity: 5,
    img: "https://rukminim2.flixcart.com/image/612/612/jzu60sw0/vitamin-supplement/n/t/y/390-c4-original-pre-workout-icy-blue-razz-60-servings-cellucor-original-imafdzqzheanqqeh.jpeg?q=70",
    rating: 4.8,
    newArrival: false,
  },
  {
    _id: uuid(),
    fastDelivery: false,
    price: "800",
    originalPrice: "1400",
    categoryName: "BCAAs",
    brand: "Big Muscles",
    stockQuantity: 0,
    img: "https://rukminim2.flixcart.com/image/612/612/kbv4fww0/protein-supplement/j/x/u/real-bmnbcaa01-bigmuscles-nutrition-original-imaft4cqznjzshme.jpeg?q=70",
    rating: 4.3,
    newArrival: false,
  },
  {
    _id: uuid(),
    fastDelivery: false,
    price: "900",
    originalPrice: "1700",
    categoryName: "Mass Gainer",
    brand: "Big Muscles",
    stockQuantity: 5,
    img: "https://rukminim2.flixcart.com/image/612/612/kfzq8i80/protein-supplement/r/h/k/real-mass-gainer-bmn312-bigmuscles-nutrition-original-imafwbv9jpth8hjy.jpeg?q=70",
    rating: 1.8,
    newArrival: false,
  },
  {
    _id: uuid(),
    fastDelivery: true,
    price: "7000",
    originalPrice: "8000",
    categoryName: "Whey Protein",
    brand: "Big Muscles",
    stockQuantity: 5,
    img: "https://rukminim2.flixcart.com/image/612/612/kzhbfrk0/protein-supplement/j/f/u/whey-protein-essential-whey-protein-24g-protein-with-digestive-original-imagbhfxkt2btg6n.jpeg?q=70",
    rating: 2.8,
    newArrival: false,
  },
  {
    _id: uuid(),
    fastDelivery: false,
    price: "1800",
    originalPrice: "3200",
    categoryName: "PreWorkout",
    brand: "Muscle Blaze",
    stockQuantity: 5,
    img: " https://rukminim2.flixcart.com/image/612/612/k4a7c7k0/protein-supplement/v/m/v/gold-gainer-xxl-nut6234-03-muscleblaze-original-imafn7dgft9y9qee.jpeg?q=70",
    rating: 3.1,
    newArrival: false,
  },
  {
    _id: uuid(),
    fastDelivery: false,
    price: "1800",
    originalPrice: "4000",
    categoryName: "BCAAs",
    brand: "Muscle Blaze",
    stockQuantity: 0,
    img: "https://rukminim2.flixcart.com/image/612/612/kuh9yfk0/protein-supplement/v/g/1/bcaa-bcaa-pro-powerful-intra-workout-with-7g-vegan-bcaas-1168-50-original-imag7h75asg3xm6h.jpeg?q=70",
    rating: 2.2,
    newArrival: false,
  },

  {
    _id: uuid(),
    fastDelivery: false,
    price: "3000",
    originalPrice: "6000",
    categoryName: "PreWorkout",
    brand: "Big Muscles",
    stockQuantity: 5,
    img: "https://rukminim2.flixcart.com/image/612/612/k4yhtow0/protein-supplement/z/s/j/freak-sydney-sunset-30-bmn181-bigmuscles-nutrition-original-imafnqgphzagz9ah.jpeg?q=70",
    rating: 3.5,
    newArrival: false,
  },
  {
    _id: uuid(),
    fastDelivery: false,
    price: "8500",
    originalPrice: "10000",
    categoryName: "Whey Protein",
    brand: "ON Nutrition",
    stockQuantity: 5,
    img: "https://rukminim2.flixcart.com/image/612/612/ksyz8280/protein-supplement/i/f/z/whey-protein-on-gold-standard-100-protein-powder-primary-source-original-imag6ffthehdnszp.jpeg?q=70",
    rating: 3.8,
    newArrival: false,
  },
];
